### ISSUE TITLE
Explore metadata using the CLI

### ISSUE THREAD

**Issue by wmeints** [wmeints/observatory#6]
We want to add commands to explore metadata for experiments so developers can see what is currently stored for the machine learning project they are working.

**Requirements**
- [x] #15 List all models
- [x] #17 List all versions for a model
- [x] #18 List all experiments for a version of a model
- [x] #19 List all runs for an experiment (ID, start, end, status only)
- [x] #19 Get details of a run including metrics, recorded outputs and settings

**Comment by MichielLangen** [comment]
All requirements are met for issue, it will now be closed
