### ISSUE TITLE
Remove recorded metadata using the CLI

### ISSUE THREAD

**Issue by wmeints** [wmeints/observatory#7]
We want to expand the CLI so developers can remove recorded metadata should they no longer need it.

**Requirements**
- [x] You can remove models
- [x] You can remove versions
- [x] You can remove experiments
- [x] You can remove runs

**Comment by MichielLangen** [comment]
All requirements are met for issue, it will now be closed
