### ISSUE TITLE
Allow recording metadata without using the observatory server

### ISSUE THREAD

**Issue by wmeints** [wmeints/observatory#8]
Right now the application requires a developer to run the server before he/she can record metadata for machine learning experiments. We want to change this so that you can record metadata for your experiments without running the server. You can still run the server, but it's not required to get started.

**Requirements**
- [x] #11 When you use observatory in your python code it should record the metadata locally 
- [x] #12 You should be able to switch to a server by configuring observatory in your training script
- [x] #13 When you use observatory without configuring, it should just work and use sensible defaults

**Comment by MichielLangen** [comment]
All requirements are met for issue, it will now be closed
