### ISSUE TITLE
Replace elasticsearch storage with a local variant

### ISSUE THREAD

**Issue by wmeints** [wmeints/observatory#9]
We no longer want to force the developer to use ElasticSearch so we can store experiment data. We need to come up with a storage mechanism that is fast and efficient to store experiment data on both the server and the local workstation.

**Requirements**
- [x] The new storage mechanism is used on server and the local workstation
- [x] The new storage mechanism is proven to be fast enough to handle up to 1M records
- [x] #14 The new storage mechanism stores data in the `.observatory` folder in the current working directory

**Comment by MichielLangen** [comment]
All requirements are met for issue, it will now be closed
